(()=>{const $=s=>document.querySelector(s);let db,lastRows=null,charts=[];
const esc=x=>String(x??"NULL").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function boot(){try{const SQL=await initSqlJs({locateFile:f=>"https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.13.0/"+f});db=new SQL.Database();seed();schema();$("#status").textContent="Ready · SQLite runs locally in your browser";run()}catch(e){$("#status").textContent="Could not load SQLite: "+e.message}}
function seed(){db.run("CREATE TABLE customers(id INTEGER,name TEXT,country TEXT);INSERT INTO customers VALUES(1,'Aarav Mehta','India'),(2,'Kabir Singh','India'),(3,'Maya Chen','Singapore'),(4,'Isha Rao','India'),(5,'Rohan Das','UAE');CREATE TABLE orders(order_id INTEGER,customer_id INTEGER,amount REAL,order_date TEXT);INSERT INTO orders VALUES(101,1,1200,'2026-01-12'),(102,2,800,'2026-01-15'),(103,3,1850,'2026-01-21'),(104,1,2750,'2026-02-03'),(105,2,2650,'2026-02-08'),(106,4,2100,'2026-02-11'),(107,3,250,'2026-02-14'),(108,5,2650,'2026-02-19');")}
function schema(){const q=db.exec("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")[0],s=$("#schema");s.innerHTML=q.values.map(r=>"<button class=tableBtn data-table='"+esc(r[0])+"'>▣ "+esc(r[0])+"</button>").join("");s.querySelectorAll(".tableBtn").forEach(b=>b.onclick=()=>{$("#sql").value="SELECT * FROM ["+b.dataset.table+"] LIMIT 100;";run()})}
function run(){try{const t=performance.now(),r=db.exec($("#sql").value)[0];$("#time").textContent=(performance.now()-t).toFixed(1)+" ms";if(!r){lastRows=null;$("#meta").textContent="0 rows";$("#results").innerHTML="<p>No rows returned.</p>";return}lastRows=r;$("#meta").textContent=r.values.length+" rows";$("#results").innerHTML="<table><thead><tr>"+r.columns.map(c=>"<th>"+esc(c)+"</th>").join("")+"</tr></thead><tbody>"+r.values.map(row=>"<tr>"+row.map(v=>"<td>"+esc(v)+"</td>").join("")+"</tr>").join("")+"</tbody></table>";buildCharts(r)}catch(e){$("#results").innerHTML="<p class=err>"+esc(e.message)+"</p>"}}
function csv(r){return [r.columns,...r.values].map(row=>row.map(v=>'"'+String(v??"").replaceAll('"','""')+'"').join(",")).join("\n")}
function download(name,text,type="text/csv"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportResults(){if(lastRows)download("query-results.csv",csv(lastRows))}
function exportTable(){const q=db.exec("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")[0];const name=prompt("Table name",q.values[0][0]);if(!name)return;const r=db.exec("SELECT * FROM ["+name+"]")[0];if(r)download(name+".csv",csv(r))}
async function upload(f){const n=f.name.toLowerCase();if(n.endsWith(".csv")){const text=await f.text(),a=text.trim().split(/\r?\n/).map(line=>line.split(","));load(f.name,a)}else if(n.endsWith(".xlsx")||n.endsWith(".xls")){const w=XLSX.read(await f.arrayBuffer());w.SheetNames.forEach(s=>load(s,w.Sheets[s]&&XLSX.utils.sheet_to_json(w.Sheets[s],{header:1,defval:null})))}}
function load(name,a){if(!a||!a.length)return;const tn=name.replace(/\W+/g,"_").slice(0,40)||"dataset",cols=a[0].map((x,i)=>String(x||"column_"+(i+1)).replace(/\W+/g,"_"));db.run("DROP TABLE IF EXISTS ["+tn+"]");db.run("CREATE TABLE ["+tn+"]("+cols.map(c=>"["+c+"] TEXT").join(",")+")");const st=db.prepare("INSERT INTO ["+tn+"] VALUES("+cols.map(()=>"?").join(",")+")");a.slice(1).forEach(r=>st.run(cols.map((_,i)=>r[i]??null)));st.free();schema();$("#sql").value="SELECT * FROM ["+tn+"] LIMIT 100;";run();$("#status").textContent="Loaded "+name+" · local SQLite table created"}
function chartData(r){if(!r||r.values.length<1||r.columns.length<2)return null;let x=0,y=1;for(let i=0;i<r.columns.length;i++){if(r.values.every(v=>!isNaN(Number(v[i])))){y=i;break}}let data=r.values.map(v=>({label:String(v[x]),value:Number(v[y])})).filter(v=>Number.isFinite(v.value)).slice(0,30);return data.length?data:null}
function buildCharts(r){const box=$("#charts");if(!box)return;box.innerHTML="";charts.forEach(c=>c.destroy());charts=[];const data=chartData(r);if(!data){box.innerHTML="<p class=muted>Run a query with at least one category column and one numeric column to generate charts.</p>";return}const types=["bar","line","pie","doughnut","polarArea","radar","horizontalBar","area","stacked","scatter"];types.forEach((type,i)=>{const card=document.createElement("article");card.className="chartCard";card.innerHTML="<div class=chartTitle>"+(i+1)+". "+type+"<button class=btn small>Export PNG</button></div><canvas></canvas>";box.appendChild(card);let ctx=card.querySelector("canvas");let chartType=type==="horizontalBar"?"bar":type==="area"||type==="stacked"?"line":type==="scatter"?"scatter":type;let config={type:chartType,data:{labels:data.map(x=>x.label),datasets:[{label:r.columns[1],data:data.map(x=>x.value),fill:type==="area",backgroundColor:type==="pie"||type==="doughnut"||type==="polarArea"?undefined:"rgba(20,20,20,.72)",borderColor:"#171717",tension:.25}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==="pie"||type==="doughnut"||type==="polarArea"}},scales:{x:{display:type!=="pie"&&type!=="doughnut"&&type!=="polarArea"&&type!=="radar"},y:{beginAtZero:true}}}};if(type==="scatter")config.data={datasets:[{label:r.columns[1],data:data.map((x,j)=>({x:j,y:x.value}))}]};if(type==="horizontalBar")config.options.indexAxis="y";if(type==="stacked"){config.data.datasets=[{label:"Value",data:data.map(x=>x.value),backgroundColor:"#171717"}];config.options.scales.x.stacked=true;config.options.scales.y.stacked=true}let ch=new Chart(ctx,config);charts.push(ch);card.querySelector("button").onclick=()=>download("chart-"+(i+1)+".png",dataURLtoBlob(ch.toBase64Image()),"image/png")})}
function dataURLtoBlob(u){return fetch(u).then(r=>r.blob())}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("on",x===b));document.querySelectorAll(".view").forEach(x=>x.hidden=x.id!==b.dataset.view)});
$("#run").onclick=run;$("#export").onclick=exportResults;$("#exportTable").onclick=exportTable;const up=e=>[...e.target.files].forEach(upload);$("#upload").onchange=up;$("#upload2").onchange=up;$("#sql").onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){e.preventDefault();run()}};boot()})();