(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let db=null,lastRows=null,charts=[],activeChartData=null,queryHistory=[],savedQueries=[];
const STORE="analyst_sql_workbench_v2",HISTORY="analyst_sql_history_v2",SAVED="analyst_sql_saved_v2";
const esc=x=>String(x??"NULL").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const ident=s=>"\""+String(s).replaceAll('"','""')+"\"";
const slug=s=>String(s||"dataset").trim().replace(/[^\w]+/g,"_").replace(/^_+|_+$/g,"").slice(0,55)||"dataset";
const TYPES=[["bar","Bar"],["line","Line"],["pie","Pie"],["doughnut","Doughnut"],["polarArea","Polar area"],["radar","Radar"],["horizontalBar","Horizontal bar"],["area","Area"],["stacked","Stacked bar"],["scatter","Scatter"]];
function status(msg,kind=""){const n=$("#status");n.textContent=msg;n.className="status "+kind}
function download(name,data,type="text/plain;charset=utf-8"){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function toB64(bytes){let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function fromB64(s){const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
function persistDb(){try{if(db){const bytes=db.export();localStorage.setItem(STORE,toB64(bytes));if(window.SQL){try{db.close()}catch(_){}db=new window.SQL.Database(bytes)}}}catch(e){status("Database is active, but browser storage is full. Export your database to keep a backup.","error")}}
function persistList(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(e){}}
function readList(key){try{const x=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(x)?x:[]}catch(e){return[]}}
function seed(){db.run("CREATE TABLE customers(customer_id INTEGER PRIMARY KEY,name TEXT,country TEXT);INSERT INTO customers VALUES(1,'Aarav Mehta','India'),(2,'Kabir Singh','India'),(3,'Maya Chen','Singapore'),(4,'Isha Rao','India'),(5,'Rohan Das','UAE'),(6,'Neha Shah','India');CREATE TABLE orders(order_id INTEGER PRIMARY KEY,customer_id INTEGER,amount REAL,order_date TEXT);INSERT INTO orders VALUES(101,1,1200,'2026-01-12'),(102,2,800,'2026-01-15'),(103,3,1850,'2026-01-21'),(104,1,2750,'2026-02-03'),(105,2,2650,'2026-02-08'),(106,4,2100,'2026-02-11'),(107,3,250,'2026-02-14'),(108,6,2650,'2026-02-19'),(109,5,1725,'2026-02-23'),(110,4,825,'2026-03-02');CREATE TABLE employees(employee_id INTEGER PRIMARY KEY,name TEXT,department TEXT,salary INTEGER);INSERT INTO employees VALUES(1,'Priya Nair','Analytics',145000),(2,'Arjun Rao','Analytics',118000),(3,'Meera Shah','Analytics',97000),(4,'Daniel Kim','Engineering',152000),(5,'Lena Ortiz','Engineering',139000),(6,'Omar Ali','Engineering',121000),(7,'Sofia Chen','Product',128000),(8,'Vikram Das','Product',111000);")}
function switchView(id){$$("[data-view]").forEach(b=>b.classList.toggle("on",b.dataset.view===id));$$(".view").forEach(v=>{v.hidden=v.id!==id});$("#pageTitle").textContent=({query:"SQL Workspace",data:"Data explorer",learn:"Learn SQL",saved:"Saved queries & history"})[id]||"SQL Workspace";if(id==="data")renderTables()}
function tables(){try{return db.exec("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")[0]?.values.map(r=>r[0])||[]}catch(e){return[]}}
function tableInfo(name){try{return db.exec("PRAGMA table_info("+ident(name)+")")[0]?.values.map(r=>({name:r[1],type:r[2]||"ANY"}))||[]}catch(e){return[]}}
function schema(){const s=$("#schema"),names=tables();const tc=$("#tableCount");if(tc)tc.textContent=String(names.length);s.innerHTML=names.length?names.map(n=>{const cols=tableInfo(n);return '<div class="schema-entry"><button class="tableBtn" data-table="'+esc(n)+'"><span>▦ '+esc(n)+'</span><small>'+cols.length+' columns</small></button><div class="schema-cols">'+cols.map(c=>esc(c.name)+' <span>'+esc(c.type)+'</span>').join("<br>")+'</div></div>'}).join(""):'<p class="muted small">No tables yet. Upload a file or reset to sample data.</p>';s.querySelectorAll("[data-table]").forEach(b=>b.onclick=()=>{$("#sql").value="SELECT * FROM "+ident(b.dataset.table)+" LIMIT 100;";switchView("query");run()})}
function csv(r){const cell=v=>{const s=String(v??"");return /[",\r\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s};return [r.columns,...r.values].map(row=>row.map(cell).join(",")).join("\r\n")}
function displayRows(r){const box=$("#results");if(!r){box.innerHTML='<div class="empty">Query completed. No result set was returned. Data-changing statements can still succeed.</div>';return}const cols=r.columns,vals=r.values;box.innerHTML='<div class="table-wrap"><table class="data-table"><thead><tr>'+cols.map(c=>'<th>'+esc(c)+'</th>').join("")+'</tr></thead><tbody>'+vals.slice(0,5000).map(row=>'<tr>'+row.map(v=>'<td>'+esc(v)+'</td>').join("")+'</tr>').join("")+'</tbody></table></div>'+(vals.length>5000?'<p class="muted small">Showing first 5,000 of '+vals.length+' rows. Export includes all rows.</p>':"");if(!vals.length)box.innerHTML='<div class="empty">Query returned zero rows.</div>'}
function renderKpis(r,ms){const box=$("#queryKpis");if(!box)return;if(!r){box.innerHTML="";return}const numeric=r.columns.map((name,i)=>({name,i,values:r.values.map(row=>row[i]).filter(v=>v!==null&&v!==""&&String(v).trim()!==""&&Number.isFinite(Number(v))).map(Number)})).filter(x=>x.values.length>0);const n=numeric[0];const cards=[["Result rows",r.values.length.toLocaleString()],["Columns",String(r.columns.length)],["Numeric fields",String(numeric.length)],[n?("Sum · "+n.name):"Query time",n?n.values.reduce((a,b)=>a+b,0).toLocaleString(undefined,{maximumFractionDigits:2}):ms.toFixed(1)+" ms"]];box.innerHTML=cards.map(([label,value])=>'<div class="stat"><small>'+esc(label)+'</small><strong>'+esc(value)+'</strong></div>').join("")}
function renderResult(r,ms){lastRows=r||null;renderKpis(r,ms);lastRows=r||null;const rc=$("#resultCount");if(rc)rc.textContent=r?r.values.length.toLocaleString():"—";$("#meta").textContent=r?r.values.length.toLocaleString()+" rows · "+r.columns.length+" columns":"Statement completed";$("#time").textContent=ms.toFixed(1)+" ms";displayRows(r);buildCharts(r);if(r)status("Query completed successfully","good");}
function addHistory(sql,ok,ms){queryHistory.unshift({sql,ok,ms:new Date().toISOString()});queryHistory=queryHistory.slice(0,40);persistList(HISTORY,queryHistory);renderHistory()}
function run(){if(!db){status("SQLite is still loading","error");return}const sql=$("#sql").value.trim();if(!sql){status("Enter a SQL query first","error");return}const t=performance.now();try{const res=db.exec(sql);const ms=performance.now()-t;const r=res.length?res[res.length-1]:null;renderResult(r,ms);schema();persistDb();addHistory(sql,true,ms)}catch(e){const ms=performance.now()-t;$("#results").innerHTML='<div class="empty error-text">'+esc(e.message)+'</div>';$("#meta").textContent="Query failed";$("#time").textContent=ms.toFixed(1)+" ms";status(e.message,"error");addHistory(sql,false,ms)}}
function exportResults(){if(!lastRows){status("Run a SELECT query before exporting results","error");return}download("query-results.csv",csv(lastRows),"text/csv;charset=utf-8")}
function exportDatabase(){if(!db)return;const bytes=db.export();if(window.SQL){try{db.close()}catch(_){}db=new window.SQL.Database(bytes)}download("analyst-workspace.sqlite",bytes,"application/octet-stream")}
function exportTable(){const name=$("#tableExportSelect").value;if(!name){status("Choose a table first","error");return}try{const r=db.exec("SELECT * FROM "+ident(name))[0];if(r)download(slug(name)+".csv",csv(r),"text/csv;charset=utf-8")}catch(e){status(e.message,"error")}}
function inferType(values){const v=values.filter(x=>x!==null&&x!=="");if(!v.length)return"TEXT";if(v.every(x=>typeof x==="number"||(/^[-+]?\d+(\.\d+)?$/.test(String(x).trim()))))return"REAL";if(v.every(x=>/^(true|false)$/i.test(String(x))))return"TEXT";return"TEXT"}
function normalizeHeaders(header){const used=new Set();return header.map((h,i)=>{let s=String(h??"").trim()||"column_"+(i+1);s=s.replace(/[\u0000-\u001f]/g," ").slice(0,120);let n=s,k=2;while(used.has(n.toLowerCase()))n=s+"_"+k++;used.add(n.toLowerCase());return n})}
function createTableFromRows(name,rows){if(!db)throw Error("SQLite has not initialized");if(!rows||!rows.length)throw Error("The file or worksheet is empty");const headers=normalizeHeaders(rows[0]||[]);if(!headers.length)throw Error("No columns found");const body=rows.slice(1).filter(r=>r.some(v=>v!==null&&v!==undefined&&String(v)!==""));const types=headers.map((_,i)=>inferType(body.map(r=>r[i])));const tn=slug(name);db.run("DROP TABLE IF EXISTS "+ident(tn));db.run("CREATE TABLE "+ident(tn)+" ("+headers.map((h,i)=>ident(h)+" "+types[i]).join(",")+")");if(body.length){const st=db.prepare("INSERT INTO "+ident(tn)+" VALUES ("+headers.map(()=>"?").join(",")+")");try{db.run("BEGIN");for(const row of body)st.run(headers.map((_,i)=>{const v=row[i];if(v===undefined||v==="")return null;if(types[headers.indexOf(headers[i])]==="REAL"&&typeof v==="string"&&v.trim()!=="")return Number(v);return v}));db.run("COMMIT")}catch(e){try{db.run("ROLLBACK")}catch(_){}throw e}finally{st.free()}}return {name:tn,rows:body.length,columns:headers.length}}
async function uploadFiles(files){if(!files?.length)return;for(const f of files){if(f.size>25*1024*1024){status(f.name+" exceeds the 25 MB per-file limit","error");continue}try{const w=XLSX.read(await f.arrayBuffer(),{type:"array",cellDates:false});if(f.name.toLowerCase().endsWith(".csv")||f.name.toLowerCase().endsWith(".txt")){const sh=w.SheetNames[0];const rows=XLSX.utils.sheet_to_json(w.Sheets[sh],{header:1,defval:null,raw:true});const out=createTableFromRows(f.name.replace(/\.[^.]+$/,""),rows);status("Imported "+out.name+" · "+out.rows.toLocaleString()+" rows · "+out.columns+" columns","good")}else{for(const sh of w.SheetNames){const rows=XLSX.utils.sheet_to_json(w.Sheets[sh],{header:1,defval:null,raw:true});if(!rows.length)continue;const out=createTableFromRows(f.name.replace(/\.[^.]+$/,"")+"_"+sh,rows);status("Imported worksheet "+sh+" as "+out.name,"good")}}}catch(e){status("Could not import "+f.name+": "+e.message,"error")}}schema();persistDb();renderTables();switchView("data")}
function renderTables(){if(!db)return;const names=tables();$("#tableList").innerHTML=names.length?names.map(n=>{const info=tableInfo(n);let count="";try{count=db.exec("SELECT COUNT(*) FROM "+ident(n))[0].values[0][0]}catch(e){}return '<div class="table-item"><div><strong>'+esc(n)+'</strong><small>'+info.length+' columns · '+Number(count).toLocaleString()+' rows</small></div><div class="toolbar-group"><button class="btn" data-preview="'+esc(n)+'">Preview</button><button class="btn" data-query="'+esc(n)+'">Query</button><button class="btn" data-delete="'+esc(n)+'">Drop</button></div></div>'}).join(""):'<div class="empty">No tables found.</div>';const sel=$("#tableExportSelect");sel.innerHTML='<option value="">Export table…</option>'+names.map(n=>'<option value="'+esc(n)+'">'+esc(n)+'</option>').join("");$("#tableList").querySelectorAll("[data-preview]").forEach(b=>b.onclick=()=>{switchView("query");$("#sql").value="SELECT * FROM "+ident(b.dataset.preview)+" LIMIT 100;";run()});$("#tableList").querySelectorAll("[data-query]").forEach(b=>b.onclick=()=>{switchView("query");$("#sql").value="SELECT * FROM "+ident(b.dataset.query)+" LIMIT 100;";run()});$("#tableList").querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{if(confirm("Drop table "+b.dataset.delete+"? This cannot be undone unless you exported a backup.")){try{db.run("DROP TABLE "+ident(b.dataset.delete));persistDb();schema();renderTables();status("Dropped "+b.dataset.delete,"good")}catch(e){status(e.message,"error")}}})}
function chartConfigFor(r,type,xIdx,yIdx){const labels=r.values.map(v=>String(v[xIdx]??"NULL")).slice(0,500);const values=r.values.map(v=>Number(v[yIdx])).slice(0,500);const colors=labels.map((_,i)=>"hsl("+((i*47+210)%360)+" 55% 55%)");const chartType=type==="horizontalBar"||type==="stacked"?"bar":type==="area"?"line":type;let data;if(type==="scatter"){data={datasets:[{label:r.columns[yIdx],data:r.values.slice(0,500).map((v,i)=>({x:Number(v[xIdx]),y:Number(v[yIdx])})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)),backgroundColor:"hsl(220 55% 45%)"}]}}else{data={labels,datasets:[{label:r.columns[yIdx],data:values,backgroundColor:["pie","doughnut","polarArea"].includes(type)?colors:"hsl(220 55% 45% / .78)",borderColor:"hsl(220 55% 35%)",borderWidth:1,fill:type==="area",tension:.25}]}}const noAxes=["pie","doughnut","polarArea","radar"].includes(type);const options={responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:["pie","doughnut","polarArea"].includes(type)},title:{display:true,text:type==="horizontalBar"?"Horizontal bar":type==="area"?"Area chart":type==="stacked"?"Stacked bar":type.charAt(0).toUpperCase()+type.slice(1)}},scales:noAxes?{}:{x:{stacked:type==="stacked",ticks:{maxRotation:45,autoSkip:true}},y:{beginAtZero:true,stacked:type==="stacked"}}};if(type==="horizontalBar")options.indexAxis="y";return {type:chartType,data,options}}
function buildCharts(r){const box=$("#charts");if(!box)return;if(typeof Chart==="undefined"){box.innerHTML='<div class="panel empty">Chart library did not load. Query results and CSV export are still available.</div>';return}charts.forEach(c=>{try{c.destroy()}catch(e){}});charts=[];box.innerHTML="";activeChartData=r;if(!r||r.values.length===0||r.columns.length<2){box.innerHTML='<div class="panel empty">Run a query with a category column and a numeric column to build charts.</div>';return}const numeric=r.columns.map((_,i)=>r.values.some(row=>row[i]!==null&&row[i]!==""&&Number.isFinite(Number(row[i]))&&String(row[i]).trim()!=="")&&r.values.filter(row=>row[i]!==null&&row[i]!=="").every(row=>Number.isFinite(Number(row[i]))));const xOpts=r.columns.map((c,i)=>'<option value="'+i+'">'+esc(c)+'</option>').join("");const yOpts=r.columns.map((c,i)=>'<option value="'+i+'" '+(numeric[i]?"":"disabled")+'>'+esc(c)+(numeric[i]?"":" (not numeric)")+'</option>').join("");const cards=TYPES.map((t,i)=>{const id="chart_"+i;return '<article class="panel chart-card"><div class="panel-head"><h3>'+esc(t[1])+'</h3><span class="muted small">Chart '+(i+1)+'/10</span></div><div class="chart-config"><label class="field">Category / X<select data-x="'+i+'">'+xOpts+'</select></label><label class="field">Measure / Y<select data-y="'+i+'">'+yOpts+'</select></label><label class="field">Limit<select data-limit="'+i+'"><option>10</option><option selected>30</option><option>100</option><option>500</option></select></label></div><div class="chart-canvas"><canvas id="'+id+'"></canvas></div><div class="chart-actions"><button class="btn" data-png="'+i+'">Export PNG</button></div></article>'}).join("");box.innerHTML=cards;const defaultY=numeric.findIndex(Boolean);if(defaultY<0){box.innerHTML='<div class="panel empty">No numeric measure found in this result. Choose a query with a numeric column (for example COUNT(*) or SUM(amount)).</div>';return}box.querySelectorAll("[data-y]").forEach(s=>s.value=String(defaultY));function redraw(i){const type=TYPES[i][0],xi=Number(box.querySelector('[data-x="'+i+'"]').value),yi=Number(box.querySelector('[data-y="'+i+'"]').value),limit=Number(box.querySelector('[data-limit="'+i+'"]').value);const clipped={columns:r.columns,values:r.values.slice(0,limit)};const canvas=$("#"+ "chart_"+i);if(charts[i]){charts[i].destroy();charts[i]=null}if(!numeric[yi])return;const config=chartConfigFor(clipped,type,xi,yi);charts[i]=new Chart(canvas,config)}box.querySelectorAll("select").forEach(s=>s.addEventListener("change",()=>redraw(Number(s.dataset.x??s.dataset.y??s.dataset.limit))));box.querySelectorAll("[data-png]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.png),c=charts[i];if(!c)return;const a=document.createElement("a");a.href=c.toBase64Image("image/png",1);a.download="analyst-chart-"+TYPES[i][0]+".png";a.click()});for(let i=0;i<TYPES.length;i++)redraw(i)}
function renderSaved(){savedQueries=readList(SAVED);$("#savedList").innerHTML=savedQueries.length?savedQueries.map((q,i)=>'<div class="history-row"><div style="min-width:0"><strong>'+esc(q.name)+'</strong><div class="history-sql">'+esc(q.sql)+'</div></div><div class="toolbar-group"><button class="btn" data-load-saved="'+i+'">Load</button><button class="btn" data-delete-saved="'+i+'">Delete</button></div></div>').join(""):'<div class="empty">No saved queries yet. Save one from the SQL workspace.</div>';$("#savedList").querySelectorAll("[data-load-saved]").forEach(b=>b.onclick=()=>{const q=savedQueries[Number(b.dataset.loadSaved)];$("#sql").value=q.sql;switchView("query")});$("#savedList").querySelectorAll("[data-delete-saved]").forEach(b=>b.onclick=()=>{savedQueries.splice(Number(b.dataset.deleteSaved),1);persistList(SAVED,savedQueries);renderSaved()});renderHistory()}
function renderHistory(){const box=$("#historyList");if(box)box.innerHTML=queryHistory.length?queryHistory.map((q,i)=>'<div class="history-row"><div style="min-width:0"><div class="history-sql">'+esc(q.sql)+'</div><small class="'+(q.ok?"good-text":"error-text")+'">'+(q.ok?"Success":"Error")+' · '+new Date(q.ms).toLocaleString()+'</small></div><button class="btn" data-history="'+i+'">Load</button></div>').join(""):'<div class="empty">Query history will appear here.</div>';if(box)box.querySelectorAll("[data-history]").forEach(b=>b.onclick=()=>{$("#sql").value=queryHistory[Number(b.dataset.history)].sql;switchView("query")});const recent=$("#recentHistory");if(recent)recent.innerHTML=queryHistory.slice(0,4).map((q,i)=>'<div class="history-row"><div style="min-width:0"><div class="history-sql">'+esc(q.sql)+'</div><small class="'+(q.ok?"good-text":"error-text")+'">'+(q.ok?"Success":"Error")+'</small></div><button class="btn" data-recent="'+i+'">Load</button></div>').join("")||'<div class="empty">No history yet.</div>';if(recent)recent.querySelectorAll("[data-recent]").forEach(b=>b.onclick=()=>{$("#sql").value=queryHistory[Number(b.dataset.recent)].sql;switchView("query")})}
function saveQuery(){const sql=$("#sql").value.trim();if(!sql){status("Write a query before saving it","error");return}const name=prompt("Name this query","My query");if(!name)return;savedQueries=readList(SAVED);savedQueries.unshift({name:name.trim().slice(0,80),sql,createdAt:new Date().toISOString()});savedQueries=savedQueries.slice(0,100);persistList(SAVED,savedQueries);renderSaved();status("Query saved in this browser","good")}
function resetWorkspace(){if(!confirm("Reset the workspace to the sample database? Export a backup first if you need your current tables."))return;try{if(db)db.close();db=new window.SQL.Database();seed();persistDb();schema();renderTables();$("#sql").value="SELECT * FROM customers LIMIT 100;";run();status("Workspace reset to sample data","good")}catch(e){status(e.message,"error")}}
function autocomplete(){const sql=$("#sql"),start=sql.selectionStart,end=sql.selectionEnd;const before=sql.value.slice(0,start),word=before.match(/[\w.]+$/)?.[0]||"";const candidates=[...new Set([...["SELECT","FROM","WHERE","GROUP BY","ORDER BY","HAVING","LIMIT","JOIN","LEFT JOIN","INNER JOIN","ON","AS","DISTINCT","COUNT","SUM","AVG","MIN","MAX","CASE","WHEN","THEN","ELSE","END","WITH","UNION","OVER","PARTITION BY","ROW_NUMBER","DESC","ASC"],...tables(),...tables().flatMap(t=>tableInfo(t).map(c=>c.name))])];const match=candidates.filter(c=>c.toLowerCase().startsWith(word.toLowerCase())&&c.toLowerCase()!==word.toLowerCase()).slice(0,8);let box=$("#suggestions");if(!match.length){box.hidden=true;return}box.innerHTML=match.map((v,i)=>'<button type="button" data-suggest="'+i+'">'+esc(v)+'</button>').join("");box.hidden=false;box.querySelectorAll("button").forEach((b,i)=>b.onclick=()=>{sql.setRangeText(match[i],start-word.length,end,"end");box.hidden=true;sql.focus()})}
function initEvents(){ $$("[data-view]").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$("#run").onclick=run;$("#export").onclick=exportResults;$("#exportTable").onclick=exportTable;$("#exportDb").onclick=exportDatabase;$("#saveQuery").onclick=saveQuery;$("#resetWorkspace").onclick=resetWorkspace;$("#upload").onchange=e=>uploadFiles([...e.target.files]);$("#upload2").onchange=e=>uploadFiles([...e.target.files]);const dz=$("#dropzone");["dragenter","dragover"].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add("drag")}));["dragleave","drop"].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove("drag")}));dz.addEventListener("drop",e=>uploadFiles([...e.dataTransfer.files]));$("#sql").onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){e.preventDefault();run()}if(e.key==="Tab"){e.preventDefault();const s=e.target.selectionStart;e.target.setRangeText("  ",s,e.target.selectionEnd,"end")}};$("#sql").addEventListener("input",()=>{clearTimeout(window.__suggestTimer);window.__suggestTimer=setTimeout(autocomplete,180)});$("#sql").addEventListener("blur",()=>setTimeout(()=>$("#suggestions").hidden=true,180));$("#sql").addEventListener("focus",()=>$("#suggestions").hidden=true);$("#clearHistory").onclick=()=>{if(confirm("Clear query history?")){queryHistory=[];persistList(HISTORY,queryHistory);renderHistory()}};$("#refreshSchema").onclick=()=>schema();$("#refreshTables").onclick=()=>renderTables()}
async function boot(){initEvents();queryHistory=readList(HISTORY);savedQueries=readList(SAVED);renderSaved();try{const SQL=await initSqlJs({locateFile:f=>"https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.13.0/"+f});window.SQL=SQL;const stored=localStorage.getItem(STORE);if(stored){try{db=new SQL.Database(fromB64(stored))}catch(e){db=new SQL.Database();seed()}}else{db=new SQL.Database();seed()}schema();renderTables();$("#sql").value="SELECT c.country, COUNT(*) AS customers\nFROM customers c\nGROUP BY c.country\nORDER BY customers DESC;";status("Ready · SQLite runs locally in your browser","good");run();renderSaved()}catch(e){status("Could not load SQLite: "+e.message,"error")}}
boot();
})();